---
  - hosts: all
    become: yes
    become_method: sudo
    
    tasks:
      - name: "Added fruitshop user"
        user:
          name: fruitshop

      - name: "Copy market.tar.gz to /opt"
        copy:
          src: files/market.tar.gz
          dest: /opt/market.tar.gz
          owner: fruitshop
          group: fruitshop
          mode: '0644'

      - name: "Extract market.tar.gz in /opt"
        unarchive:
          src: /opt/market.tar.gz
          dest: /opt/
          remote_src: yes
          owner: fruitshop
          group: fruitshop

      - name: "Install required packages"
        apt:
          name:
            - libprotobuf-dev
            - libnl-route-3-dev
            - socat
            - xinetd
          state: present
          update_cache: yes
      - name: "Copy fruitshop file to /etc/xinetd.d/"
        copy:
          src: files/fruitshop
          dest: /etc/xinetd.d/fruitshop
          owner: root
          group: root
          mode: '0644'

      - name: "Copy run.sh to /opt/market"
        copy:
          src: files/run.sh
          dest: /opt/market/run.sh
          owner: fruitshop
          group: fruitshop
          mode: '0755'

      - name: "Restart xinetd service"
        systemd:
          name: xinetd
          state: restarted


