# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: checker.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rchecker.proto\x12\x07\x63hecker\"H\n\x10PlantFlagRequest\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r\x12\x0c\n\x04\x66lag\x18\x03 \x01(\t\x12\x0c\n\x04slot\x18\x04 \x01(\r\"^\n\x11PlantFlagResponse\x12&\n\x06status\x18\x01 \x01(\x0b\x32\x16.checker.ServiceStatus\x12\r\n\x05token\x18\x02 \x01(\t\x12\x12\n\nidentifier\x18\x03 \x01(\t\"E\n\rServiceStatus\x12$\n\x05state\x18\x01 \x01(\x0e\x32\x15.checker.ServiceState\x12\x0e\n\x06reason\x18\x02 \x01(\t\"k\n\x10\x43heckFlagRequest\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r\x12\x0c\n\x04\x66lag\x18\x03 \x01(\t\x12\r\n\x05token\x18\x04 \x01(\t\x12\x12\n\nidentifier\x18\x05 \x01(\t\x12\x0c\n\x04slot\x18\x06 \x01(\r\"/\n\x13\x43heckServiceRequest\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r*F\n\x0cServiceState\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x06\n\x02UP\x10\x01\x12\x08\n\x04\x44OWN\x10\x02\x12\n\n\x06MUMBLE\x10\x03\x12\x0b\n\x07\x43ORRUPT\x10\x04\x32\xd3\x01\n\x07\x43hecker\x12\x42\n\tPlantFlag\x12\x19.checker.PlantFlagRequest\x1a\x1a.checker.PlantFlagResponse\x12>\n\tCheckFlag\x12\x19.checker.CheckFlagRequest\x1a\x16.checker.ServiceStatus\x12\x44\n\x0c\x43heckService\x12\x1c.checker.CheckServiceRequest\x1a\x16.checker.ServiceStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'checker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERVICESTATE']._serialized_start=425
  _globals['_SERVICESTATE']._serialized_end=495
  _globals['_PLANTFLAGREQUEST']._serialized_start=26
  _globals['_PLANTFLAGREQUEST']._serialized_end=98
  _globals['_PLANTFLAGRESPONSE']._serialized_start=100
  _globals['_PLANTFLAGRESPONSE']._serialized_end=194
  _globals['_SERVICESTATUS']._serialized_start=196
  _globals['_SERVICESTATUS']._serialized_end=265
  _globals['_CHECKFLAGREQUEST']._serialized_start=267
  _globals['_CHECKFLAGREQUEST']._serialized_end=374
  _globals['_CHECKSERVICEREQUEST']._serialized_start=376
  _globals['_CHECKSERVICEREQUEST']._serialized_end=423
  _globals['_CHECKER']._serialized_start=498
  _globals['_CHECKER']._serialized_end=709
# @@protoc_insertion_point(module_scope)
