# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import checker_pb2 as checker__pb2

GRPC_GENERATED_VERSION = '1.65.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in checker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class CheckerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PlantFlag = channel.unary_unary(
                '/checker.Checker/PlantFlag',
                request_serializer=checker__pb2.PlantFlagRequest.SerializeToString,
                response_deserializer=checker__pb2.PlantFlagResponse.FromString,
                _registered_method=True)
        self.CheckFlag = channel.unary_unary(
                '/checker.Checker/CheckFlag',
                request_serializer=checker__pb2.CheckFlagRequest.SerializeToString,
                response_deserializer=checker__pb2.ServiceStatus.FromString,
                _registered_method=True)
        self.CheckService = channel.unary_unary(
                '/checker.Checker/CheckService',
                request_serializer=checker__pb2.CheckServiceRequest.SerializeToString,
                response_deserializer=checker__pb2.ServiceStatus.FromString,
                _registered_method=True)


class CheckerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PlantFlag(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckFlag(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CheckerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PlantFlag': grpc.unary_unary_rpc_method_handler(
                    servicer.PlantFlag,
                    request_deserializer=checker__pb2.PlantFlagRequest.FromString,
                    response_serializer=checker__pb2.PlantFlagResponse.SerializeToString,
            ),
            'CheckFlag': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckFlag,
                    request_deserializer=checker__pb2.CheckFlagRequest.FromString,
                    response_serializer=checker__pb2.ServiceStatus.SerializeToString,
            ),
            'CheckService': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckService,
                    request_deserializer=checker__pb2.CheckServiceRequest.FromString,
                    response_serializer=checker__pb2.ServiceStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'checker.Checker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('checker.Checker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Checker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PlantFlag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/checker.Checker/PlantFlag',
            checker__pb2.PlantFlagRequest.SerializeToString,
            checker__pb2.PlantFlagResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckFlag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/checker.Checker/CheckFlag',
            checker__pb2.CheckFlagRequest.SerializeToString,
            checker__pb2.ServiceStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/checker.Checker/CheckService',
            checker__pb2.CheckServiceRequest.SerializeToString,
            checker__pb2.ServiceStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
